----- BEVERAGE_CART -----
-- DROP
DROP SEQUENCE SEQ_BEVERAGE_CART_NO;

DROP TABLE BEVERAGE_CART CASCADE CONSTRAINTS;



-- CREATE
CREATE SEQUENCE SEQ_BEVERAGE_CART_NO NOCACHE NOCYCLE;

CREATE TABLE BEVERAGE_CART (
	BEVERAGE_CART_NO	NUMBER	CONSTRAINT PK_BEVERAGE_CART_NO PRIMARY KEY
    , MEMBER_NO	        NUMBER	CONSTRAINT NN_BEV_CART_MEMBER_NO NOT NULL
    , BEV_NO	        NUMBER	CONSTRAINT NN_BEV_NO NOT NULL
    , BEV_COUNT	        CHAR(5) CONSTRAINT NN_BEV_COUNT NOT NULL
    , BEV_SUM	        NUMBER	CONSTRAINT NN_BEV_SUM NOT NULL
    , BEV_REQUEST	    VARCHAR2(4000)
);



-- INSERT
INSERT INTO BEVERAGE_CART (
    BEVERAGE_CART_NO
    , MEMBER_NO
    , BEV_NO
    , BEV_COUNT
    , BEV_SUM
    , BEV_REQUEST
)
VALUES (
    SEQ_BEVERAGE_CART_NO.NEXTVAL
    , 2
    , 1
    , 2
    , 9000
    , '모두 진하게'
);

INSERT INTO BEVERAGE_CART (
    BEVERAGE_CART_NO
    , MEMBER_NO
    , BEV_NO
    , BEV_COUNT
    , BEV_SUM
    , BEV_REQUEST
)
VALUES (
    SEQ_BEVERAGE_CART_NO.NEXTVAL
    , 2
    , 4
    , 5
    , 29500
    , '모두 샷 추가'
);

INSERT INTO BEVERAGE_CART (
    BEVERAGE_CART_NO
    , MEMBER_NO
    , BEV_NO
    , BEV_COUNT
    , BEV_SUM
    , BEV_REQUEST
)
VALUES (
    SEQ_BEVERAGE_CART_NO.NEXTVAL
    , 2
    , 8
    , 1
    , 6900
    , '덜 달게'
);



----- FOOD_CART -----
-- DROP
DROP SEQUENCE SEQ_FOOD_CART_NO;

DROP TABLE FOOD_CART CASCADE CONSTRAINTS;



-- CREATE
CREATE SEQUENCE SEQ_FOOD_CART_NO NOCACHE NOCYCLE;

CREATE TABLE FOOD_CART (
	FOOD_CART_NO	NUMBER	CONSTRAINT PK_FOOD_CART_NO PRIMARY KEY
    , MEMBER_NO	    NUMBER	CONSTRAINT NN_MEMBER_NO_FOOD NOT NULL
    , FOOD_NO	    NUMBER	CONSTRAINT NN_FOOD_NO NOT NULL
    , FOOD_COUNT    CHAR(5)	CONSTRAINT NN_FOOD_COUNT NOT NULL
    , FOOD_SUM	    NUMBER	CONSTRAINT NN_FOOD_SUM NOT NULL
    , FOOD_REQUEST	VARCHAR2(4000)	NOT NULL
);



-- INSERT
INSERT INTO FOOD_CART (
    FOOD_CART_NO
    , MEMBER_NO
    , FOOD_NO
    , FOOD_COUNT
    , FOOD_SUM
    , FOOD_REQUEST
)
VALUES (
    SEQ_FOOD_CART_NO.NEXTVAL
    , 2
    , 4
    , 2
    , 11400
    , '부서지지 않게 조심히 ...'
);

INSERT INTO FOOD_CART (
    FOOD_CART_NO
    , MEMBER_NO
    , FOOD_NO
    , FOOD_COUNT
    , FOOD_SUM
    , FOOD_REQUEST
)
VALUES (
    SEQ_FOOD_CART_NO.NEXTVAL
    , 2
    , 7
    , 4
    , 22000
    , '넵킨 5장 부탁드려요 !!!'
);



----- MERCHANDISE_CART -----
-- DROP
DROP SEQUENCE SEQ_MERCHANDISE_CART_NO;

DROP TABLE MERCHANDISE_CART CASCADE CONSTRAINTS;



-- CREATE
CREATE SEQUENCE SEQ_MERCHANDISE_CART_NO NOCACHE NOCYCLE;

CREATE TABLE MERCHANDISE_CART (
    MERCHANDISE_CART_NO     NUMBER          CONSTRAINT PK_MERCHANDISE_CART_MERCHANDISE_CART_NO PRIMARY KEY
   , MEMBER_NO              NUMBER          CONSTRAINT NN_MERCHANDISE_CART_MEMBER_NO NOT NULL
   , MD_NO                  NUMBER          CONSTRAINT NN_MERCHANDISE_CART_MD_NO NOT NULL
   , MD_COUNT               CHAR(5)         CONSTRAINT NN_MERCHANDISE_CART_MD_COUNT NOT NULL
   , MD_SUM                 NUMBER          CONSTRAINT NN_MERCHANDISE_CART_MD_SUM NOT NULL
   , MD_REQUEST             VARCHAR2(4000)
);



-- INSERT
INSERT INTO MERCHANDISE_CART (
    MERCHANDISE_CART_NO
    , MEMBER_NO
    , MD_NO
    , MD_COUNT
    , MD_SUM
    , MD_REQUEST
)
VALUES (
    SEQ_MERCHANDISE_CART_NO.NEXTVAL
    , 2
    , 3
    , 2
    , 78000
    , '선물용으로 포장해주세요 ~~~'
);

COMMIT;
